"""
generate_report.py
====================
Build a quoting-reference PDF from geometry_extract.json + the rendered
views/flat_pattern images. Fully data-driven -- no part-specific values.

Usage:
    python3 generate_report.py geometry_extract.json --views views/ \
        --flatpattern flat_pattern.png --out report.pdf
"""
import argparse
import json
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from PIL import Image


def make_report(json_path, views_dir, flat_pattern_path, out_path):
    with open(json_path) as f:
        g = json.load(f)

    PAGE_W, PAGE_H = 17*inch, 11*inch
    c = canvas.Canvas(out_path, pagesize=(PAGE_W, PAGE_H))
    margin = 0.4*inch

    def frame():
        c.setLineWidth(1.2)
        c.rect(margin, margin, PAGE_W-2*margin, PAGE_H-2*margin)

    def header(title, subtitle):
        c.setFont("Helvetica-Bold", 15)
        c.drawString(margin+0.2*inch, PAGE_H-margin-0.32*inch, title)
        c.setFont("Helvetica-Bold", 8.5)
        c.setFillColor(colors.HexColor("#1a5f1a"))
        c.drawString(margin+0.2*inch, PAGE_H-margin-0.53*inch, subtitle)
        c.setFillColor(colors.black)
        c.setLineWidth(0.75)
        c.line(margin+0.1*inch, PAGE_H-margin-0.63*inch, PAGE_W-margin-0.1*inch, PAGE_H-margin-0.63*inch)

    def box(x, y, w, h, label=None):
        c.setLineWidth(0.6)
        c.rect(x, y, w, h)
        if label:
            c.setFont("Helvetica-Bold", 9)
            c.drawString(x+4, y+h-13, label)

    def place_image(path, x, y, w, h, pad_top=16, pad=6):
        im = Image.open(path)
        iw, ih = im.size
        avail_w, avail_h = w-2*pad, h-pad_top-pad
        scale = min(avail_w/iw, avail_h/ih)
        dw, dh = iw*scale, ih*scale
        c.drawImage(path, x+(w-dw)/2, y+pad, width=dw, height=dh, preserveAspectRatio=True, mask='auto')

    def table(x, y, w, rows, col_fracs, row_h=16, font=8):
        n = len(rows)
        total_h = row_h*n
        xs = [x]
        cx = x
        for fr in col_fracs:
            cx += w*fr
            xs.append(cx)
        c.setFillColor(colors.HexColor("#e8e8e8"))
        c.rect(x, y, w, row_h, fill=1, stroke=0)
        c.setFillColor(colors.black)
        c.setLineWidth(0.5)
        c.rect(x, y-total_h+row_h, w, total_h)
        for xi in xs[1:-1]:
            c.line(xi, y-total_h+row_h, xi, y+row_h)
        ry = y
        for ridx, row in enumerate(rows):
            if ridx > 0:
                c.line(x, ry, x+w, ry)
            for ci, val in enumerate(row):
                c.setFont("Helvetica-Bold" if ridx == 0 else "Helvetica", font)
                c.drawString(xs[ci]+5, ry-row_h+5, str(val))
            ry -= row_h
        return y-total_h

    part_name = g.get("source_file", "part")

    # ---------------- PAGE 1: envelope + bend table ----------------
    frame()
    header(f"{part_name} \u2014 Geometry-Derived Quoting Data (STEP file only)",
           "Computed directly from the solid: face classification, bend detection, cross-section unfold, feature clustering")

    y = PAGE_H - margin - 1.0*inch
    env = g["envelope"]
    env_rows = [
        ["Property", "Value"],
        ["Overall length (X)", f"{env['bbox_mm']['xlen']/25.4:.2f} in"],
        ["Overall width (Y)", f"{env['bbox_mm']['ylen']/25.4:.2f} in"],
        ["Overall height (Z)", f"{env['bbox_mm']['zlen']/25.4:.2f} in"],
        ["Sheet thickness (derived)", f"{g['thickness_in']:.4f} in"],
        ["Bend radius (derived)", f"{g['bend_radius_in']:.3f} in" if g['bend_radius_in'] else "n/a"],
        ["Number of bends detected", f"{g['num_bends']}"],
        ["Bend angles (deg)", ", ".join(str(a) for a in g["bend_angles_deg"])],
        ["Computed flat/developed width", f"{g['flat_width_in']:.2f} in (K={g['k_factor_assumed']})"],
        ["Solid volume", f"{env['volume_cm3']:.1f} cm3"],
        ["Est. weight", f"{env['mass_lb']:.2f} lb ({env['mass_kg']:.2f} kg)"],
    ]
    y_after = table(margin, y, (PAGE_W-2*margin), env_rows, [0.45, 0.55])
    y = y_after - 0.3*inch

    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "FEATURE SUMMARY (auto-classified)")
    y -= 0.26*inch
    from collections import Counter
    type_counts = Counter(f["type"] for f in g["features"])
    feat_rows = [["Feature type", "Count found"]]
    for t, n in type_counts.items():
        feat_rows.append([t, n])
    feat_rows.append(["Unclassified (needs manual review)", g.get("features_unclassified_count", 0)])
    table(margin, y, (PAGE_W-2*margin)*0.5, feat_rows, [0.6, 0.4])

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(margin, margin+0.15*inch,
      "Auto-generated by step_quote_extract.py -- see INSTRUCTIONS.md for what to sanity-check before using for CAM.")
    c.setFillColor(colors.black)
    c.showPage()

    # ---------------- PAGE 2: views + flat pattern ----------------
    frame()
    header(f"{part_name} \u2014 Views & Computed Flat Pattern", "")
    content_top = PAGE_H - margin - 0.7*inch
    half_h = (content_top - margin - 0.2*inch) / 2 - 0.1*inch

    box(margin, content_top-half_h, (PAGE_W-2*margin)*0.5-0.1*inch, half_h, "ISOMETRIC")
    place_image(f"{views_dir}/view_iso.png", margin, content_top-half_h, (PAGE_W-2*margin)*0.5-0.1*inch, half_h)
    box(margin+(PAGE_W-2*margin)*0.5+0.1*inch, content_top-half_h, (PAGE_W-2*margin)*0.5-0.1*inch, half_h, "TOP")
    place_image(f"{views_dir}/view_top.png", margin+(PAGE_W-2*margin)*0.5+0.1*inch, content_top-half_h,
                (PAGE_W-2*margin)*0.5-0.1*inch, half_h)

    y2 = content_top - half_h - 0.2*inch
    box(margin, y2-half_h, PAGE_W-2*margin, half_h, "COMPUTED FLAT PATTERN")
    place_image(flat_pattern_path, margin, y2-half_h, PAGE_W-2*margin, half_h)
    c.showPage()

    # ---------------- PAGE 3: full feature table ----------------
    frame()
    header(f"{part_name} \u2014 Hole/Feature Position Table", "(Length, Transverse) in inches on the developed flat pattern")
    y = PAGE_H - margin - 1.0*inch
    rows = [["Type", "Length (in)", "Transverse (in)", "Size"]]
    for f in g["features"]:
        if f["type"] == "slot":
            size = f"{f.get('width_in','?')} x {f.get('slot_length_in','?')} in"
        elif "diameter_in" in f:
            size = f"\u2205{f['diameter_in']} in"
        elif "size_in" in f:
            size = f"{f['size_in'][0]} x {f['size_in'][1]} in"
        else:
            size = "-"
        rows.append([f["type"], f.get("length_in","-"), f.get("transverse_in","-"), size])
    half = len(rows)//2 + 1
    left, right = [rows[0]]+rows[1:half], [rows[0]]+rows[half:]
    col_w = (PAGE_W-2*margin-0.3*inch)/2
    table(margin, y, col_w, left, [0.34,0.22,0.22,0.22], row_h=15, font=8)
    table(margin+col_w+0.3*inch, y, col_w, right, [0.34,0.22,0.22,0.22], row_h=15, font=8)
    c.showPage()

    c.save()
    print("saved", out_path)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path")
    ap.add_argument("--views", default="views")
    ap.add_argument("--flatpattern", default="flat_pattern.png")
    ap.add_argument("--out", default="report.pdf")
    args = ap.parse_args()
    make_report(args.json_path, args.views, args.flatpattern, args.out)
